### ISSUE TITLE
Rewrite in rust

### ISSUE THREAD

**Issue by Taha-Firoz** [SaadBazaz/UrduPython#2]
Please, use nom

**Comment by SaadBazaz** [comment]
Hey @Taha-Firoz,

The benefits of Python really surpass any other language for this specific project. Ranging from; 1) UrduPython runs on Python under-the-hood and so it benefits it to be in Python as well, 2) Python is high-level and I am aiming for a trickle-down effect (i.e. from high-level language localization to lower-level language localization), 3) Assuming users already have Python installed in their systems, it's best off that UrduPython is in Python as well.

Maybe it could be looked into later, when the implementation is solid and it really needs optimization.
